export enum DataAttr {
  Split = "data-split",
  MarqueeTrack = "data-marquee-track",
  VinylPin = "data-vinyl-pin",
  VinylDisc = "data-vinyl-disc",
  VinylMask = "data-vinyl-mask",
  VinylTitle = "data-vinyl-title",
  VinylCopy = "data-vinyl-copy",
  VinylGhost = "data-vinyl-ghost",
  VinylRule = "data-vinyl-rule",
  VinylGlow = "data-vinyl-glow",
  ListenItem = "data-listen-item",
  Overlay = "data-overlay",
  OverlayLink = "data-overlay-link",
  HeroPhoto = "data-hero-photo",
  HeroTitle = "data-hero-title",
  HeroPiano = "data-hero-piano",
  HeroFrame = "data-hero-frame",
  HeroKey = "data-hero-key",
  HeroBlackKey = "data-hero-black-key",
  HeroShutters = "data-hero-shutters",
  HeroShutter = "data-hero-shutter",
  CtaArrow = "data-cta-arrow",
}
